//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBAPI.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public string CustID { get; set; }
        public string ProdID { get; set; }
        public System.DateTime OrderDate { get; set; }
        public int Quantity { get; set; }
        public Nullable<System.DateTime> ShipDate { get; set; }
        public string ShipMode { get; set; }
        [JsonIgnore]
        public virtual Customer Customer { get; set; }
        [JsonIgnore]
        public virtual Product Product { get; set; }
        [JsonIgnore]
        public virtual Shipping Shipping { get; set; }
    }
}
